/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated from: src/styles/_theme.sass
 * Generated on: 2025-10-22T13:58:33.930Z
 *
 * This file is automatically generated during the build process.
 * To update: Edit the source SASS files and run `npm run extract:tokens`
 */

export interface DesignToken {
  name: string;
  category: string;
  subcategory?: string;
  description: string;
  example?: string;
  usage: string;
}

export const TOKEN_CATEGORIES = {
  BORDER: 'Border',
  FILL: 'Fill',
  TEXT: 'Text',
  SURFACE: 'Surface',
  SPACING: 'Spacing',
  RADIUS: 'Border Radius',
  SIZE: 'Size',
  TYPOGRAPHY: 'Typography',
  SHADOW: 'Shadow',
  ICON: 'Icon',
  INPUT: 'Input',
  TRANSITION: 'Transition',
  OPACITY: 'Opacity',
  OTHER: 'Other'
} as const;

export const tokens: DesignToken[] = [
  {
    "name": "--lb-border-primary-line",
    "category": "Border",
    "subcategory": "primary",
    "description": "Primary border color for line state",
    "usage": "border: 1px solid var(--lb-border-primary-line);",
    "example": "Use for primary border in line state"
  },
  {
    "name": "--lb-border-primary-normal",
    "category": "Border",
    "subcategory": "primary",
    "description": "Primary border color for normal state",
    "usage": "border: 1px solid var(--lb-border-primary-normal);",
    "example": "Use for primary border in normal state"
  },
  {
    "name": "--lb-border-primary-active",
    "category": "Border",
    "subcategory": "primary",
    "description": "Primary border color for active state",
    "usage": "border: 1px solid var(--lb-border-primary-active);",
    "example": "Use for primary border in active state"
  },
  {
    "name": "--lb-border-primary-focus",
    "category": "Border",
    "subcategory": "primary",
    "description": "Primary border color for focus state",
    "usage": "border: 1px solid var(--lb-border-primary-focus);",
    "example": "Use for primary border in focus state"
  },
  {
    "name": "--lb-border-primary-disabled",
    "category": "Border",
    "subcategory": "primary",
    "description": "Primary border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-primary-disabled);",
    "example": "Use for primary border in disabled state"
  },
  {
    "name": "--lb-border-secondary-line",
    "category": "Border",
    "subcategory": "secondary",
    "description": "Secondary border color for line state",
    "usage": "border: 1px solid var(--lb-border-secondary-line);",
    "example": "Use for secondary border in line state"
  },
  {
    "name": "--lb-border-secondary-normal",
    "category": "Border",
    "subcategory": "secondary",
    "description": "Secondary border color for normal state",
    "usage": "border: 1px solid var(--lb-border-secondary-normal);",
    "example": "Use for secondary border in normal state"
  },
  {
    "name": "--lb-border-secondary-active",
    "category": "Border",
    "subcategory": "secondary",
    "description": "Secondary border color for active state",
    "usage": "border: 1px solid var(--lb-border-secondary-active);",
    "example": "Use for secondary border in active state"
  },
  {
    "name": "--lb-border-secondary-focus",
    "category": "Border",
    "subcategory": "secondary",
    "description": "Secondary border color for focus state",
    "usage": "border: 1px solid var(--lb-border-secondary-focus);",
    "example": "Use for secondary border in focus state"
  },
  {
    "name": "--lb-border-secondary-disabled",
    "category": "Border",
    "subcategory": "secondary",
    "description": "Secondary border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-secondary-disabled);",
    "example": "Use for secondary border in disabled state"
  },
  {
    "name": "--lb-border-tertiary-line",
    "category": "Border",
    "subcategory": "tertiary",
    "description": "Tertiary border color for line state",
    "usage": "border: 1px solid var(--lb-border-tertiary-line);",
    "example": "Use for tertiary border in line state"
  },
  {
    "name": "--lb-border-tertiary-normal",
    "category": "Border",
    "subcategory": "tertiary",
    "description": "Tertiary border color for normal state",
    "usage": "border: 1px solid var(--lb-border-tertiary-normal);",
    "example": "Use for tertiary border in normal state"
  },
  {
    "name": "--lb-border-tertiary-active",
    "category": "Border",
    "subcategory": "tertiary",
    "description": "Tertiary border color for active state",
    "usage": "border: 1px solid var(--lb-border-tertiary-active);",
    "example": "Use for tertiary border in active state"
  },
  {
    "name": "--lb-border-tertiary-focus",
    "category": "Border",
    "subcategory": "tertiary",
    "description": "Tertiary border color for focus state",
    "usage": "border: 1px solid var(--lb-border-tertiary-focus);",
    "example": "Use for tertiary border in focus state"
  },
  {
    "name": "--lb-border-tertiary-disabled",
    "category": "Border",
    "subcategory": "tertiary",
    "description": "Tertiary border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-tertiary-disabled);",
    "example": "Use for tertiary border in disabled state"
  },
  {
    "name": "--lb-border-success-line",
    "category": "Border",
    "subcategory": "success",
    "description": "Success border color for line state",
    "usage": "border: 1px solid var(--lb-border-success-line);",
    "example": "Use for success border in line state"
  },
  {
    "name": "--lb-border-success-normal",
    "category": "Border",
    "subcategory": "success",
    "description": "Success border color for normal state",
    "usage": "border: 1px solid var(--lb-border-success-normal);",
    "example": "Use for success border in normal state"
  },
  {
    "name": "--lb-border-success-active",
    "category": "Border",
    "subcategory": "success",
    "description": "Success border color for active state",
    "usage": "border: 1px solid var(--lb-border-success-active);",
    "example": "Use for success border in active state"
  },
  {
    "name": "--lb-border-success-focus",
    "category": "Border",
    "subcategory": "success",
    "description": "Success border color for focus state",
    "usage": "border: 1px solid var(--lb-border-success-focus);",
    "example": "Use for success border in focus state"
  },
  {
    "name": "--lb-border-success-disabled",
    "category": "Border",
    "subcategory": "success",
    "description": "Success border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-success-disabled);",
    "example": "Use for success border in disabled state"
  },
  {
    "name": "--lb-border-warning-line",
    "category": "Border",
    "subcategory": "warning",
    "description": "Warning border color for line state",
    "usage": "border: 1px solid var(--lb-border-warning-line);",
    "example": "Use for warning border in line state"
  },
  {
    "name": "--lb-border-warning-normal",
    "category": "Border",
    "subcategory": "warning",
    "description": "Warning border color for normal state",
    "usage": "border: 1px solid var(--lb-border-warning-normal);",
    "example": "Use for warning border in normal state"
  },
  {
    "name": "--lb-border-warning-active",
    "category": "Border",
    "subcategory": "warning",
    "description": "Warning border color for active state",
    "usage": "border: 1px solid var(--lb-border-warning-active);",
    "example": "Use for warning border in active state"
  },
  {
    "name": "--lb-border-warning-focus",
    "category": "Border",
    "subcategory": "warning",
    "description": "Warning border color for focus state",
    "usage": "border: 1px solid var(--lb-border-warning-focus);",
    "example": "Use for warning border in focus state"
  },
  {
    "name": "--lb-border-warning-disabled",
    "category": "Border",
    "subcategory": "warning",
    "description": "Warning border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-warning-disabled);",
    "example": "Use for warning border in disabled state"
  },
  {
    "name": "--lb-border-error-line",
    "category": "Border",
    "subcategory": "error",
    "description": "Error border color for line state",
    "usage": "border: 1px solid var(--lb-border-error-line);",
    "example": "Use for error border in line state"
  },
  {
    "name": "--lb-border-error-normal",
    "category": "Border",
    "subcategory": "error",
    "description": "Error border color for normal state",
    "usage": "border: 1px solid var(--lb-border-error-normal);",
    "example": "Use for error border in normal state"
  },
  {
    "name": "--lb-border-error-active",
    "category": "Border",
    "subcategory": "error",
    "description": "Error border color for active state",
    "usage": "border: 1px solid var(--lb-border-error-active);",
    "example": "Use for error border in active state"
  },
  {
    "name": "--lb-border-error-focus",
    "category": "Border",
    "subcategory": "error",
    "description": "Error border color for focus state",
    "usage": "border: 1px solid var(--lb-border-error-focus);",
    "example": "Use for error border in focus state"
  },
  {
    "name": "--lb-border-error-disabled",
    "category": "Border",
    "subcategory": "error",
    "description": "Error border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-error-disabled);",
    "example": "Use for error border in disabled state"
  },
  {
    "name": "--lb-border-info-line",
    "category": "Border",
    "subcategory": "info",
    "description": "Info border color for line state",
    "usage": "border: 1px solid var(--lb-border-info-line);",
    "example": "Use for info border in line state"
  },
  {
    "name": "--lb-border-info-normal",
    "category": "Border",
    "subcategory": "info",
    "description": "Info border color for normal state",
    "usage": "border: 1px solid var(--lb-border-info-normal);",
    "example": "Use for info border in normal state"
  },
  {
    "name": "--lb-border-info-active",
    "category": "Border",
    "subcategory": "info",
    "description": "Info border color for active state",
    "usage": "border: 1px solid var(--lb-border-info-active);",
    "example": "Use for info border in active state"
  },
  {
    "name": "--lb-border-info-focus",
    "category": "Border",
    "subcategory": "info",
    "description": "Info border color for focus state",
    "usage": "border: 1px solid var(--lb-border-info-focus);",
    "example": "Use for info border in focus state"
  },
  {
    "name": "--lb-border-info-disabled",
    "category": "Border",
    "subcategory": "info",
    "description": "Info border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-info-disabled);",
    "example": "Use for info border in disabled state"
  },
  {
    "name": "--lb-border-neutral-line",
    "category": "Border",
    "subcategory": "neutral",
    "description": "Neutral border color for line state",
    "usage": "border: 1px solid var(--lb-border-neutral-line);",
    "example": "Use for neutral border in line state"
  },
  {
    "name": "--lb-border-neutral-normal",
    "category": "Border",
    "subcategory": "neutral",
    "description": "Neutral border color for normal state",
    "usage": "border: 1px solid var(--lb-border-neutral-normal);",
    "example": "Use for neutral border in normal state"
  },
  {
    "name": "--lb-border-neutral-active",
    "category": "Border",
    "subcategory": "neutral",
    "description": "Neutral border color for active state",
    "usage": "border: 1px solid var(--lb-border-neutral-active);",
    "example": "Use for neutral border in active state"
  },
  {
    "name": "--lb-border-neutral-focus",
    "category": "Border",
    "subcategory": "neutral",
    "description": "Neutral border color for focus state",
    "usage": "border: 1px solid var(--lb-border-neutral-focus);",
    "example": "Use for neutral border in focus state"
  },
  {
    "name": "--lb-border-neutral-disabled",
    "category": "Border",
    "subcategory": "neutral",
    "description": "Neutral border color for disabled state",
    "usage": "border: 1px solid var(--lb-border-neutral-disabled);",
    "example": "Use for neutral border in disabled state"
  },
  {
    "name": "--lb-fill-primary-normal",
    "category": "Fill",
    "subcategory": "primary",
    "description": "Primary fill/background color for normal state",
    "usage": "background: var(--lb-fill-primary-normal);",
    "example": "Background color for primary element in normal state"
  },
  {
    "name": "--lb-fill-primary-hover",
    "category": "Fill",
    "subcategory": "primary",
    "description": "Primary fill/background color for hover state",
    "usage": "background: var(--lb-fill-primary-hover);",
    "example": "Background color for primary element in hover state"
  },
  {
    "name": "--lb-fill-primary-active",
    "category": "Fill",
    "subcategory": "primary",
    "description": "Primary fill/background color for active state",
    "usage": "background: var(--lb-fill-primary-active);",
    "example": "Background color for primary element in active state"
  },
  {
    "name": "--lb-fill-primary-disabled",
    "category": "Fill",
    "subcategory": "primary",
    "description": "Primary fill/background color for disabled state",
    "usage": "background: var(--lb-fill-primary-disabled);",
    "example": "Background color for primary element in disabled state"
  },
  {
    "name": "--lb-fill-secondary-normal",
    "category": "Fill",
    "subcategory": "secondary",
    "description": "Secondary fill/background color for normal state",
    "usage": "background: var(--lb-fill-secondary-normal);",
    "example": "Background color for secondary element in normal state"
  },
  {
    "name": "--lb-fill-secondary-hover",
    "category": "Fill",
    "subcategory": "secondary",
    "description": "Secondary fill/background color for hover state",
    "usage": "background: var(--lb-fill-secondary-hover);",
    "example": "Background color for secondary element in hover state"
  },
  {
    "name": "--lb-fill-secondary-active",
    "category": "Fill",
    "subcategory": "secondary",
    "description": "Secondary fill/background color for active state",
    "usage": "background: var(--lb-fill-secondary-active);",
    "example": "Background color for secondary element in active state"
  },
  {
    "name": "--lb-fill-secondary-disabled",
    "category": "Fill",
    "subcategory": "secondary",
    "description": "Secondary fill/background color for disabled state",
    "usage": "background: var(--lb-fill-secondary-disabled);",
    "example": "Background color for secondary element in disabled state"
  },
  {
    "name": "--lb-fill-tertiary-normal",
    "category": "Fill",
    "subcategory": "tertiary",
    "description": "Tertiary fill/background color for normal state",
    "usage": "background: var(--lb-fill-tertiary-normal);",
    "example": "Background color for tertiary element in normal state"
  },
  {
    "name": "--lb-fill-tertiary-hover",
    "category": "Fill",
    "subcategory": "tertiary",
    "description": "Tertiary fill/background color for hover state",
    "usage": "background: var(--lb-fill-tertiary-hover);",
    "example": "Background color for tertiary element in hover state"
  },
  {
    "name": "--lb-fill-tertiary-active",
    "category": "Fill",
    "subcategory": "tertiary",
    "description": "Tertiary fill/background color for active state",
    "usage": "background: var(--lb-fill-tertiary-active);",
    "example": "Background color for tertiary element in active state"
  },
  {
    "name": "--lb-fill-tertiary-disabled",
    "category": "Fill",
    "subcategory": "tertiary",
    "description": "Tertiary fill/background color for disabled state",
    "usage": "background: var(--lb-fill-tertiary-disabled);",
    "example": "Background color for tertiary element in disabled state"
  },
  {
    "name": "--lb-fill-success-normal",
    "category": "Fill",
    "subcategory": "success",
    "description": "Success fill/background color for normal state",
    "usage": "background: var(--lb-fill-success-normal);",
    "example": "Background color for success element in normal state"
  },
  {
    "name": "--lb-fill-success-hover",
    "category": "Fill",
    "subcategory": "success",
    "description": "Success fill/background color for hover state",
    "usage": "background: var(--lb-fill-success-hover);",
    "example": "Background color for success element in hover state"
  },
  {
    "name": "--lb-fill-success-active",
    "category": "Fill",
    "subcategory": "success",
    "description": "Success fill/background color for active state",
    "usage": "background: var(--lb-fill-success-active);",
    "example": "Background color for success element in active state"
  },
  {
    "name": "--lb-fill-success-disabled",
    "category": "Fill",
    "subcategory": "success",
    "description": "Success fill/background color for disabled state",
    "usage": "background: var(--lb-fill-success-disabled);",
    "example": "Background color for success element in disabled state"
  },
  {
    "name": "--lb-fill-warning-normal",
    "category": "Fill",
    "subcategory": "warning",
    "description": "Warning fill/background color for normal state",
    "usage": "background: var(--lb-fill-warning-normal);",
    "example": "Background color for warning element in normal state"
  },
  {
    "name": "--lb-fill-warning-hover",
    "category": "Fill",
    "subcategory": "warning",
    "description": "Warning fill/background color for hover state",
    "usage": "background: var(--lb-fill-warning-hover);",
    "example": "Background color for warning element in hover state"
  },
  {
    "name": "--lb-fill-warning-active",
    "category": "Fill",
    "subcategory": "warning",
    "description": "Warning fill/background color for active state",
    "usage": "background: var(--lb-fill-warning-active);",
    "example": "Background color for warning element in active state"
  },
  {
    "name": "--lb-fill-warning-disabled",
    "category": "Fill",
    "subcategory": "warning",
    "description": "Warning fill/background color for disabled state",
    "usage": "background: var(--lb-fill-warning-disabled);",
    "example": "Background color for warning element in disabled state"
  },
  {
    "name": "--lb-fill-error-normal",
    "category": "Fill",
    "subcategory": "error",
    "description": "Error fill/background color for normal state",
    "usage": "background: var(--lb-fill-error-normal);",
    "example": "Background color for error element in normal state"
  },
  {
    "name": "--lb-fill-error-hover",
    "category": "Fill",
    "subcategory": "error",
    "description": "Error fill/background color for hover state",
    "usage": "background: var(--lb-fill-error-hover);",
    "example": "Background color for error element in hover state"
  },
  {
    "name": "--lb-fill-error-active",
    "category": "Fill",
    "subcategory": "error",
    "description": "Error fill/background color for active state",
    "usage": "background: var(--lb-fill-error-active);",
    "example": "Background color for error element in active state"
  },
  {
    "name": "--lb-fill-error-disabled",
    "category": "Fill",
    "subcategory": "error",
    "description": "Error fill/background color for disabled state",
    "usage": "background: var(--lb-fill-error-disabled);",
    "example": "Background color for error element in disabled state"
  },
  {
    "name": "--lb-fill-info-normal",
    "category": "Fill",
    "subcategory": "info",
    "description": "Info fill/background color for normal state",
    "usage": "background: var(--lb-fill-info-normal);",
    "example": "Background color for info element in normal state"
  },
  {
    "name": "--lb-fill-info-hover",
    "category": "Fill",
    "subcategory": "info",
    "description": "Info fill/background color for hover state",
    "usage": "background: var(--lb-fill-info-hover);",
    "example": "Background color for info element in hover state"
  },
  {
    "name": "--lb-fill-info-active",
    "category": "Fill",
    "subcategory": "info",
    "description": "Info fill/background color for active state",
    "usage": "background: var(--lb-fill-info-active);",
    "example": "Background color for info element in active state"
  },
  {
    "name": "--lb-fill-info-disabled",
    "category": "Fill",
    "subcategory": "info",
    "description": "Info fill/background color for disabled state",
    "usage": "background: var(--lb-fill-info-disabled);",
    "example": "Background color for info element in disabled state"
  },
  {
    "name": "--lb-fill-neutral-normal",
    "category": "Fill",
    "subcategory": "neutral",
    "description": "Neutral fill/background color for normal state",
    "usage": "background: var(--lb-fill-neutral-normal);",
    "example": "Background color for neutral element in normal state"
  },
  {
    "name": "--lb-fill-neutral-hover",
    "category": "Fill",
    "subcategory": "neutral",
    "description": "Neutral fill/background color for hover state",
    "usage": "background: var(--lb-fill-neutral-hover);",
    "example": "Background color for neutral element in hover state"
  },
  {
    "name": "--lb-fill-neutral-active",
    "category": "Fill",
    "subcategory": "neutral",
    "description": "Neutral fill/background color for active state",
    "usage": "background: var(--lb-fill-neutral-active);",
    "example": "Background color for neutral element in active state"
  },
  {
    "name": "--lb-fill-neutral-disabled",
    "category": "Fill",
    "subcategory": "neutral",
    "description": "Neutral fill/background color for disabled state",
    "usage": "background: var(--lb-fill-neutral-disabled);",
    "example": "Background color for neutral element in disabled state"
  },
  {
    "name": "--lb-text-primary-normal",
    "category": "Text",
    "subcategory": "primary",
    "description": "Primary text color (normal contrast)",
    "usage": "color: var(--lb-text-primary-normal);",
    "example": "Text color for primary content"
  },
  {
    "name": "--lb-text-primary-contrast-high",
    "category": "Text",
    "subcategory": "primary",
    "description": "Primary text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-primary-contrast-high);",
    "example": "Text color for primary content"
  },
  {
    "name": "--lb-text-primary-contrast-low",
    "category": "Text",
    "subcategory": "primary",
    "description": "Primary text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-primary-contrast-low);",
    "example": "Text color for primary content"
  },
  {
    "name": "--lb-text-primary-disabled",
    "category": "Text",
    "subcategory": "primary",
    "description": "Primary text color (disabled contrast)",
    "usage": "color: var(--lb-text-primary-disabled);",
    "example": "Text color for primary content"
  },
  {
    "name": "--lb-text-secondary-normal",
    "category": "Text",
    "subcategory": "secondary",
    "description": "Secondary text color (normal contrast)",
    "usage": "color: var(--lb-text-secondary-normal);",
    "example": "Text color for secondary content"
  },
  {
    "name": "--lb-text-secondary-contrast-high",
    "category": "Text",
    "subcategory": "secondary",
    "description": "Secondary text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-secondary-contrast-high);",
    "example": "Text color for secondary content"
  },
  {
    "name": "--lb-text-secondary-contrast-low",
    "category": "Text",
    "subcategory": "secondary",
    "description": "Secondary text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-secondary-contrast-low);",
    "example": "Text color for secondary content"
  },
  {
    "name": "--lb-text-secondary-disabled",
    "category": "Text",
    "subcategory": "secondary",
    "description": "Secondary text color (disabled contrast)",
    "usage": "color: var(--lb-text-secondary-disabled);",
    "example": "Text color for secondary content"
  },
  {
    "name": "--lb-text-tertiary-normal",
    "category": "Text",
    "subcategory": "tertiary",
    "description": "Tertiary text color (normal contrast)",
    "usage": "color: var(--lb-text-tertiary-normal);",
    "example": "Text color for tertiary content"
  },
  {
    "name": "--lb-text-tertiary-contrast-high",
    "category": "Text",
    "subcategory": "tertiary",
    "description": "Tertiary text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-tertiary-contrast-high);",
    "example": "Text color for tertiary content"
  },
  {
    "name": "--lb-text-tertiary-contrast-low",
    "category": "Text",
    "subcategory": "tertiary",
    "description": "Tertiary text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-tertiary-contrast-low);",
    "example": "Text color for tertiary content"
  },
  {
    "name": "--lb-text-tertiary-disabled",
    "category": "Text",
    "subcategory": "tertiary",
    "description": "Tertiary text color (disabled contrast)",
    "usage": "color: var(--lb-text-tertiary-disabled);",
    "example": "Text color for tertiary content"
  },
  {
    "name": "--lb-text-success-normal",
    "category": "Text",
    "subcategory": "success",
    "description": "Success text color (normal contrast)",
    "usage": "color: var(--lb-text-success-normal);",
    "example": "Text color for success content"
  },
  {
    "name": "--lb-text-success-contrast-high",
    "category": "Text",
    "subcategory": "success",
    "description": "Success text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-success-contrast-high);",
    "example": "Text color for success content"
  },
  {
    "name": "--lb-text-success-contrast-low",
    "category": "Text",
    "subcategory": "success",
    "description": "Success text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-success-contrast-low);",
    "example": "Text color for success content"
  },
  {
    "name": "--lb-text-success-disabled",
    "category": "Text",
    "subcategory": "success",
    "description": "Success text color (disabled contrast)",
    "usage": "color: var(--lb-text-success-disabled);",
    "example": "Text color for success content"
  },
  {
    "name": "--lb-text-warning-normal",
    "category": "Text",
    "subcategory": "warning",
    "description": "Warning text color (normal contrast)",
    "usage": "color: var(--lb-text-warning-normal);",
    "example": "Text color for warning content"
  },
  {
    "name": "--lb-text-warning-contrast-high",
    "category": "Text",
    "subcategory": "warning",
    "description": "Warning text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-warning-contrast-high);",
    "example": "Text color for warning content"
  },
  {
    "name": "--lb-text-warning-contrast-low",
    "category": "Text",
    "subcategory": "warning",
    "description": "Warning text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-warning-contrast-low);",
    "example": "Text color for warning content"
  },
  {
    "name": "--lb-text-warning-disabled",
    "category": "Text",
    "subcategory": "warning",
    "description": "Warning text color (disabled contrast)",
    "usage": "color: var(--lb-text-warning-disabled);",
    "example": "Text color for warning content"
  },
  {
    "name": "--lb-text-error-normal",
    "category": "Text",
    "subcategory": "error",
    "description": "Error text color (normal contrast)",
    "usage": "color: var(--lb-text-error-normal);",
    "example": "Text color for error content"
  },
  {
    "name": "--lb-text-error-contrast-high",
    "category": "Text",
    "subcategory": "error",
    "description": "Error text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-error-contrast-high);",
    "example": "Text color for error content"
  },
  {
    "name": "--lb-text-error-contrast-low",
    "category": "Text",
    "subcategory": "error",
    "description": "Error text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-error-contrast-low);",
    "example": "Text color for error content"
  },
  {
    "name": "--lb-text-error-disabled",
    "category": "Text",
    "subcategory": "error",
    "description": "Error text color (disabled contrast)",
    "usage": "color: var(--lb-text-error-disabled);",
    "example": "Text color for error content"
  },
  {
    "name": "--lb-text-info-normal",
    "category": "Text",
    "subcategory": "info",
    "description": "Info text color (normal contrast)",
    "usage": "color: var(--lb-text-info-normal);",
    "example": "Text color for info content"
  },
  {
    "name": "--lb-text-info-contrast-high",
    "category": "Text",
    "subcategory": "info",
    "description": "Info text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-info-contrast-high);",
    "example": "Text color for info content"
  },
  {
    "name": "--lb-text-info-contrast-low",
    "category": "Text",
    "subcategory": "info",
    "description": "Info text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-info-contrast-low);",
    "example": "Text color for info content"
  },
  {
    "name": "--lb-text-info-disabled",
    "category": "Text",
    "subcategory": "info",
    "description": "Info text color (disabled contrast)",
    "usage": "color: var(--lb-text-info-disabled);",
    "example": "Text color for info content"
  },
  {
    "name": "--lb-text-neutral-normal",
    "category": "Text",
    "subcategory": "neutral",
    "description": "Neutral text color (normal contrast)",
    "usage": "color: var(--lb-text-neutral-normal);",
    "example": "Text color for neutral content"
  },
  {
    "name": "--lb-text-neutral-contrast-high",
    "category": "Text",
    "subcategory": "neutral",
    "description": "Neutral text color (contrast-high contrast)",
    "usage": "color: var(--lb-text-neutral-contrast-high);",
    "example": "Text color for neutral content"
  },
  {
    "name": "--lb-text-neutral-contrast-low",
    "category": "Text",
    "subcategory": "neutral",
    "description": "Neutral text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-neutral-contrast-low);",
    "example": "Text color for neutral content"
  },
  {
    "name": "--lb-text-neutral-disabled",
    "category": "Text",
    "subcategory": "neutral",
    "description": "Neutral text color (disabled contrast)",
    "usage": "color: var(--lb-text-neutral-disabled);",
    "example": "Text color for neutral content"
  },
  {
    "name": "--lb-surface-base",
    "category": "Surface",
    "subcategory": "",
    "description": "Base surface background",
    "usage": "background: var(--lb-surface-base);",
    "example": "Base background surface"
  },
  {
    "name": "--lb-surface-subtle",
    "category": "Surface",
    "subcategory": "",
    "description": "Subtle surface background",
    "usage": "background: var(--lb-surface-subtle);",
    "example": "Subtle background surface"
  },
  {
    "name": "--lb-surface-disabled",
    "category": "Surface",
    "subcategory": "",
    "description": "Disabled surface background",
    "usage": "background: var(--lb-surface-disabled);",
    "example": "Disabled background surface"
  },
  {
    "name": "--lb-surface-primary-normal",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (normal state)",
    "usage": "background: var(--lb-surface-primary-normal);",
    "example": "Subtle primary background in normal state"
  },
  {
    "name": "--lb-surface-primary-hover",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (hover state)",
    "usage": "background: var(--lb-surface-primary-hover);",
    "example": "Subtle primary background in hover state"
  },
  {
    "name": "--lb-surface-primary-active",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (active state)",
    "usage": "background: var(--lb-surface-primary-active);",
    "example": "Subtle primary background in active state"
  },
  {
    "name": "--lb-surface-primary-normal-alpha",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-primary-normal-alpha);",
    "example": "Subtle primary background in normal-alpha state"
  },
  {
    "name": "--lb-surface-primary-hover-alpha",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-primary-hover-alpha);",
    "example": "Subtle primary background in hover-alpha state"
  },
  {
    "name": "--lb-surface-primary-active-alpha",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-primary-active-alpha);",
    "example": "Subtle primary background in active-alpha state"
  },
  {
    "name": "--lb-surface-primary-base-inverse",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-primary-base-inverse);",
    "example": "Subtle primary background in base-inverse state"
  },
  {
    "name": "--lb-surface-primary-subtle-inverse",
    "category": "Surface",
    "subcategory": "primary",
    "description": "Primary surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-primary-subtle-inverse);",
    "example": "Subtle primary background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-secondary-normal",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (normal state)",
    "usage": "background: var(--lb-surface-secondary-normal);",
    "example": "Subtle secondary background in normal state"
  },
  {
    "name": "--lb-surface-secondary-hover",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (hover state)",
    "usage": "background: var(--lb-surface-secondary-hover);",
    "example": "Subtle secondary background in hover state"
  },
  {
    "name": "--lb-surface-secondary-active",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (active state)",
    "usage": "background: var(--lb-surface-secondary-active);",
    "example": "Subtle secondary background in active state"
  },
  {
    "name": "--lb-surface-secondary-normal-alpha",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-secondary-normal-alpha);",
    "example": "Subtle secondary background in normal-alpha state"
  },
  {
    "name": "--lb-surface-secondary-hover-alpha",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-secondary-hover-alpha);",
    "example": "Subtle secondary background in hover-alpha state"
  },
  {
    "name": "--lb-surface-secondary-active-alpha",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-secondary-active-alpha);",
    "example": "Subtle secondary background in active-alpha state"
  },
  {
    "name": "--lb-surface-secondary-base-inverse",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-secondary-base-inverse);",
    "example": "Subtle secondary background in base-inverse state"
  },
  {
    "name": "--lb-surface-secondary-subtle-inverse",
    "category": "Surface",
    "subcategory": "secondary",
    "description": "Secondary surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-secondary-subtle-inverse);",
    "example": "Subtle secondary background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-tertiary-normal",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (normal state)",
    "usage": "background: var(--lb-surface-tertiary-normal);",
    "example": "Subtle tertiary background in normal state"
  },
  {
    "name": "--lb-surface-tertiary-hover",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (hover state)",
    "usage": "background: var(--lb-surface-tertiary-hover);",
    "example": "Subtle tertiary background in hover state"
  },
  {
    "name": "--lb-surface-tertiary-active",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (active state)",
    "usage": "background: var(--lb-surface-tertiary-active);",
    "example": "Subtle tertiary background in active state"
  },
  {
    "name": "--lb-surface-tertiary-normal-alpha",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-tertiary-normal-alpha);",
    "example": "Subtle tertiary background in normal-alpha state"
  },
  {
    "name": "--lb-surface-tertiary-hover-alpha",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-tertiary-hover-alpha);",
    "example": "Subtle tertiary background in hover-alpha state"
  },
  {
    "name": "--lb-surface-tertiary-active-alpha",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-tertiary-active-alpha);",
    "example": "Subtle tertiary background in active-alpha state"
  },
  {
    "name": "--lb-surface-tertiary-base-inverse",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-tertiary-base-inverse);",
    "example": "Subtle tertiary background in base-inverse state"
  },
  {
    "name": "--lb-surface-tertiary-subtle-inverse",
    "category": "Surface",
    "subcategory": "tertiary",
    "description": "Tertiary surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-tertiary-subtle-inverse);",
    "example": "Subtle tertiary background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-success-normal",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (normal state)",
    "usage": "background: var(--lb-surface-success-normal);",
    "example": "Subtle success background in normal state"
  },
  {
    "name": "--lb-surface-success-hover",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (hover state)",
    "usage": "background: var(--lb-surface-success-hover);",
    "example": "Subtle success background in hover state"
  },
  {
    "name": "--lb-surface-success-active",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (active state)",
    "usage": "background: var(--lb-surface-success-active);",
    "example": "Subtle success background in active state"
  },
  {
    "name": "--lb-surface-success-normal-alpha",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-success-normal-alpha);",
    "example": "Subtle success background in normal-alpha state"
  },
  {
    "name": "--lb-surface-success-hover-alpha",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-success-hover-alpha);",
    "example": "Subtle success background in hover-alpha state"
  },
  {
    "name": "--lb-surface-success-active-alpha",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-success-active-alpha);",
    "example": "Subtle success background in active-alpha state"
  },
  {
    "name": "--lb-surface-success-base-inverse",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-success-base-inverse);",
    "example": "Subtle success background in base-inverse state"
  },
  {
    "name": "--lb-surface-success-subtle-inverse",
    "category": "Surface",
    "subcategory": "success",
    "description": "Success surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-success-subtle-inverse);",
    "example": "Subtle success background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-warning-normal",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (normal state)",
    "usage": "background: var(--lb-surface-warning-normal);",
    "example": "Subtle warning background in normal state"
  },
  {
    "name": "--lb-surface-warning-hover",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (hover state)",
    "usage": "background: var(--lb-surface-warning-hover);",
    "example": "Subtle warning background in hover state"
  },
  {
    "name": "--lb-surface-warning-active",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (active state)",
    "usage": "background: var(--lb-surface-warning-active);",
    "example": "Subtle warning background in active state"
  },
  {
    "name": "--lb-surface-warning-normal-alpha",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-warning-normal-alpha);",
    "example": "Subtle warning background in normal-alpha state"
  },
  {
    "name": "--lb-surface-warning-hover-alpha",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-warning-hover-alpha);",
    "example": "Subtle warning background in hover-alpha state"
  },
  {
    "name": "--lb-surface-warning-active-alpha",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-warning-active-alpha);",
    "example": "Subtle warning background in active-alpha state"
  },
  {
    "name": "--lb-surface-warning-base-inverse",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-warning-base-inverse);",
    "example": "Subtle warning background in base-inverse state"
  },
  {
    "name": "--lb-surface-warning-subtle-inverse",
    "category": "Surface",
    "subcategory": "warning",
    "description": "Warning surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-warning-subtle-inverse);",
    "example": "Subtle warning background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-error-normal",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (normal state)",
    "usage": "background: var(--lb-surface-error-normal);",
    "example": "Subtle error background in normal state"
  },
  {
    "name": "--lb-surface-error-hover",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (hover state)",
    "usage": "background: var(--lb-surface-error-hover);",
    "example": "Subtle error background in hover state"
  },
  {
    "name": "--lb-surface-error-active",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (active state)",
    "usage": "background: var(--lb-surface-error-active);",
    "example": "Subtle error background in active state"
  },
  {
    "name": "--lb-surface-error-normal-alpha",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-error-normal-alpha);",
    "example": "Subtle error background in normal-alpha state"
  },
  {
    "name": "--lb-surface-error-hover-alpha",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-error-hover-alpha);",
    "example": "Subtle error background in hover-alpha state"
  },
  {
    "name": "--lb-surface-error-active-alpha",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-error-active-alpha);",
    "example": "Subtle error background in active-alpha state"
  },
  {
    "name": "--lb-surface-error-base-inverse",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-error-base-inverse);",
    "example": "Subtle error background in base-inverse state"
  },
  {
    "name": "--lb-surface-error-subtle-inverse",
    "category": "Surface",
    "subcategory": "error",
    "description": "Error surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-error-subtle-inverse);",
    "example": "Subtle error background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-info-normal",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (normal state)",
    "usage": "background: var(--lb-surface-info-normal);",
    "example": "Subtle info background in normal state"
  },
  {
    "name": "--lb-surface-info-hover",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (hover state)",
    "usage": "background: var(--lb-surface-info-hover);",
    "example": "Subtle info background in hover state"
  },
  {
    "name": "--lb-surface-info-active",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (active state)",
    "usage": "background: var(--lb-surface-info-active);",
    "example": "Subtle info background in active state"
  },
  {
    "name": "--lb-surface-info-normal-alpha",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-info-normal-alpha);",
    "example": "Subtle info background in normal-alpha state"
  },
  {
    "name": "--lb-surface-info-hover-alpha",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-info-hover-alpha);",
    "example": "Subtle info background in hover-alpha state"
  },
  {
    "name": "--lb-surface-info-active-alpha",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-info-active-alpha);",
    "example": "Subtle info background in active-alpha state"
  },
  {
    "name": "--lb-surface-info-base-inverse",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-info-base-inverse);",
    "example": "Subtle info background in base-inverse state"
  },
  {
    "name": "--lb-surface-info-subtle-inverse",
    "category": "Surface",
    "subcategory": "info",
    "description": "Info surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-info-subtle-inverse);",
    "example": "Subtle info background in subtle-inverse state"
  },
  {
    "name": "--lb-surface-neutral-normal",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (normal state)",
    "usage": "background: var(--lb-surface-neutral-normal);",
    "example": "Subtle neutral background in normal state"
  },
  {
    "name": "--lb-surface-neutral-hover",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (hover state)",
    "usage": "background: var(--lb-surface-neutral-hover);",
    "example": "Subtle neutral background in hover state"
  },
  {
    "name": "--lb-surface-neutral-active",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (active state)",
    "usage": "background: var(--lb-surface-neutral-active);",
    "example": "Subtle neutral background in active state"
  },
  {
    "name": "--lb-surface-neutral-normal-alpha",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (normal-alpha state)",
    "usage": "background: var(--lb-surface-neutral-normal-alpha);",
    "example": "Subtle neutral background in normal-alpha state"
  },
  {
    "name": "--lb-surface-neutral-hover-alpha",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (hover-alpha state)",
    "usage": "background: var(--lb-surface-neutral-hover-alpha);",
    "example": "Subtle neutral background in hover-alpha state"
  },
  {
    "name": "--lb-surface-neutral-active-alpha",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (active-alpha state)",
    "usage": "background: var(--lb-surface-neutral-active-alpha);",
    "example": "Subtle neutral background in active-alpha state"
  },
  {
    "name": "--lb-surface-neutral-base-inverse",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (base-inverse state)",
    "usage": "background: var(--lb-surface-neutral-base-inverse);",
    "example": "Subtle neutral background in base-inverse state"
  },
  {
    "name": "--lb-surface-neutral-subtle-inverse",
    "category": "Surface",
    "subcategory": "neutral",
    "description": "Neutral surface color (subtle-inverse state)",
    "usage": "background: var(--lb-surface-neutral-subtle-inverse);",
    "example": "Subtle neutral background in subtle-inverse state"
  },
  {
    "name": "--lb-text-on-primary",
    "category": "Text",
    "subcategory": "on-primary",
    "description": "Text color for use on primary backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-primary);",
    "example": "Text on primary button"
  },
  {
    "name": "--lb-text-on-primary-hover",
    "category": "Text",
    "subcategory": "on-primary",
    "description": "Text color for use on primary backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-primary-hover);",
    "example": "Text on primary button"
  },
  {
    "name": "--lb-text-on-primary-active",
    "category": "Text",
    "subcategory": "on-primary",
    "description": "Text color for use on primary backgrounds (active state)",
    "usage": "color: var(--lb-text-on-primary-active);",
    "example": "Text on primary button"
  },
  {
    "name": "--lb-text-on-secondary",
    "category": "Text",
    "subcategory": "on-secondary",
    "description": "Text color for use on secondary backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-secondary);",
    "example": "Text on secondary button"
  },
  {
    "name": "--lb-text-on-secondary-hover",
    "category": "Text",
    "subcategory": "on-secondary",
    "description": "Text color for use on secondary backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-secondary-hover);",
    "example": "Text on secondary button"
  },
  {
    "name": "--lb-text-on-secondary-active",
    "category": "Text",
    "subcategory": "on-secondary",
    "description": "Text color for use on secondary backgrounds (active state)",
    "usage": "color: var(--lb-text-on-secondary-active);",
    "example": "Text on secondary button"
  },
  {
    "name": "--lb-text-on-tertiary",
    "category": "Text",
    "subcategory": "on-tertiary",
    "description": "Text color for use on tertiary backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-tertiary);",
    "example": "Text on tertiary button"
  },
  {
    "name": "--lb-text-on-tertiary-hover",
    "category": "Text",
    "subcategory": "on-tertiary",
    "description": "Text color for use on tertiary backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-tertiary-hover);",
    "example": "Text on tertiary button"
  },
  {
    "name": "--lb-text-on-tertiary-active",
    "category": "Text",
    "subcategory": "on-tertiary",
    "description": "Text color for use on tertiary backgrounds (active state)",
    "usage": "color: var(--lb-text-on-tertiary-active);",
    "example": "Text on tertiary button"
  },
  {
    "name": "--lb-text-on-success",
    "category": "Text",
    "subcategory": "on-success",
    "description": "Text color for use on success backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-success);",
    "example": "Text on success button"
  },
  {
    "name": "--lb-text-on-success-hover",
    "category": "Text",
    "subcategory": "on-success",
    "description": "Text color for use on success backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-success-hover);",
    "example": "Text on success button"
  },
  {
    "name": "--lb-text-on-success-active",
    "category": "Text",
    "subcategory": "on-success",
    "description": "Text color for use on success backgrounds (active state)",
    "usage": "color: var(--lb-text-on-success-active);",
    "example": "Text on success button"
  },
  {
    "name": "--lb-text-on-warning",
    "category": "Text",
    "subcategory": "on-warning",
    "description": "Text color for use on warning backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-warning);",
    "example": "Text on warning button"
  },
  {
    "name": "--lb-text-on-warning-hover",
    "category": "Text",
    "subcategory": "on-warning",
    "description": "Text color for use on warning backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-warning-hover);",
    "example": "Text on warning button"
  },
  {
    "name": "--lb-text-on-warning-active",
    "category": "Text",
    "subcategory": "on-warning",
    "description": "Text color for use on warning backgrounds (active state)",
    "usage": "color: var(--lb-text-on-warning-active);",
    "example": "Text on warning button"
  },
  {
    "name": "--lb-text-on-error",
    "category": "Text",
    "subcategory": "on-error",
    "description": "Text color for use on error backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-error);",
    "example": "Text on error button"
  },
  {
    "name": "--lb-text-on-error-hover",
    "category": "Text",
    "subcategory": "on-error",
    "description": "Text color for use on error backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-error-hover);",
    "example": "Text on error button"
  },
  {
    "name": "--lb-text-on-error-active",
    "category": "Text",
    "subcategory": "on-error",
    "description": "Text color for use on error backgrounds (active state)",
    "usage": "color: var(--lb-text-on-error-active);",
    "example": "Text on error button"
  },
  {
    "name": "--lb-text-on-info",
    "category": "Text",
    "subcategory": "on-info",
    "description": "Text color for use on info backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-info);",
    "example": "Text on info button"
  },
  {
    "name": "--lb-text-on-info-hover",
    "category": "Text",
    "subcategory": "on-info",
    "description": "Text color for use on info backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-info-hover);",
    "example": "Text on info button"
  },
  {
    "name": "--lb-text-on-info-active",
    "category": "Text",
    "subcategory": "on-info",
    "description": "Text color for use on info backgrounds (active state)",
    "usage": "color: var(--lb-text-on-info-active);",
    "example": "Text on info button"
  },
  {
    "name": "--lb-text-on-neutral",
    "category": "Text",
    "subcategory": "on-neutral",
    "description": "Text color for use on neutral backgrounds (normal state)",
    "usage": "color: var(--lb-text-on-neutral);",
    "example": "Text on neutral button"
  },
  {
    "name": "--lb-text-on-neutral-hover",
    "category": "Text",
    "subcategory": "on-neutral",
    "description": "Text color for use on neutral backgrounds (hover state)",
    "usage": "color: var(--lb-text-on-neutral-hover);",
    "example": "Text on neutral button"
  },
  {
    "name": "--lb-text-on-neutral-active",
    "category": "Text",
    "subcategory": "on-neutral",
    "description": "Text color for use on neutral backgrounds (active state)",
    "usage": "color: var(--lb-text-on-neutral-active);",
    "example": "Text on neutral button"
  },
  {
    "name": "--lb-surface-overlay",
    "category": "Surface",
    "subcategory": "",
    "description": "Overlay surface background",
    "usage": "background: var(--lb-surface-overlay);",
    "example": "Overlay background surface"
  },
  {
    "name": "--lb-focus-ring-color",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-focus-ring-color",
    "example": ""
  },
  {
    "name": "--lb-divider-color",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-divider-color",
    "example": ""
  },
  {
    "name": "--lb-icon-size-sm",
    "category": "Icon",
    "subcategory": "",
    "description": "Icon size sm",
    "usage": "width: var(--lb-icon-size-sm); height: var(--lb-icon-size-sm);",
    "example": "Standard icon sizing"
  },
  {
    "name": "--lb-icon-size-md",
    "category": "Icon",
    "subcategory": "",
    "description": "Icon size md",
    "usage": "width: var(--lb-icon-size-md); height: var(--lb-icon-size-md);",
    "example": "Standard icon sizing"
  },
  {
    "name": "--lb-icon-size-lg",
    "category": "Icon",
    "subcategory": "",
    "description": "Icon size lg",
    "usage": "width: var(--lb-icon-size-lg); height: var(--lb-icon-size-lg);",
    "example": "Standard icon sizing"
  },
  {
    "name": "--lb-space-2xs",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 2xs",
    "usage": "padding: var(--lb-space-2xs); gap: var(--lb-space-2xs);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-xs",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size xs",
    "usage": "padding: var(--lb-space-xs); gap: var(--lb-space-xs);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-sm",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size sm",
    "usage": "padding: var(--lb-space-sm); gap: var(--lb-space-sm);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-md",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size md",
    "usage": "padding: var(--lb-space-md); gap: var(--lb-space-md);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-lg",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size lg",
    "usage": "padding: var(--lb-space-lg); gap: var(--lb-space-lg);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size xl",
    "usage": "padding: var(--lb-space-xl); gap: var(--lb-space-xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-2xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 2xl",
    "usage": "padding: var(--lb-space-2xl); gap: var(--lb-space-2xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-3xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 3xl",
    "usage": "padding: var(--lb-space-3xl); gap: var(--lb-space-3xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-4xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 4xl",
    "usage": "padding: var(--lb-space-4xl); gap: var(--lb-space-4xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-5xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 5xl",
    "usage": "padding: var(--lb-space-5xl); gap: var(--lb-space-5xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-6xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 6xl",
    "usage": "padding: var(--lb-space-6xl); gap: var(--lb-space-6xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-7xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 7xl",
    "usage": "padding: var(--lb-space-7xl); gap: var(--lb-space-7xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-8xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 8xl",
    "usage": "padding: var(--lb-space-8xl); gap: var(--lb-space-8xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-9xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 9xl",
    "usage": "padding: var(--lb-space-9xl); gap: var(--lb-space-9xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-space-10xl",
    "category": "Spacing",
    "subcategory": "",
    "description": "Spacing size 10xl",
    "usage": "padding: var(--lb-space-10xl); gap: var(--lb-space-10xl);",
    "example": "Use for margins, padding, gaps"
  },
  {
    "name": "--lb-border-sm",
    "category": "Border",
    "subcategory": "sm",
    "description": "Sm border color for  state",
    "usage": "border: 1px solid var(--lb-border-sm);",
    "example": "Use for sm border in  state"
  },
  {
    "name": "--lb-border-md",
    "category": "Border",
    "subcategory": "md",
    "description": "Md border color for  state",
    "usage": "border: 1px solid var(--lb-border-md);",
    "example": "Use for md border in  state"
  },
  {
    "name": "--lb-radius-xs",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius xs",
    "usage": "border-radius: var(--lb-radius-xs);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-sm",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius sm",
    "usage": "border-radius: var(--lb-radius-sm);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-md",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius md",
    "usage": "border-radius: var(--lb-radius-md);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-lg",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius lg",
    "usage": "border-radius: var(--lb-radius-lg);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius xl",
    "usage": "border-radius: var(--lb-radius-xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-2xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 2xl",
    "usage": "border-radius: var(--lb-radius-2xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-3xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 3xl",
    "usage": "border-radius: var(--lb-radius-3xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-4xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 4xl",
    "usage": "border-radius: var(--lb-radius-4xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-5xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 5xl",
    "usage": "border-radius: var(--lb-radius-5xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-6xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 6xl",
    "usage": "border-radius: var(--lb-radius-6xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-7xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 7xl",
    "usage": "border-radius: var(--lb-radius-7xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-8xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 8xl",
    "usage": "border-radius: var(--lb-radius-8xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-9xl",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius 9xl",
    "usage": "border-radius: var(--lb-radius-9xl);",
    "example": "Rounded corners"
  },
  {
    "name": "--lb-radius-full",
    "category": "Border Radius",
    "subcategory": "",
    "description": "Border radius full",
    "usage": "border-radius: var(--lb-radius-full);",
    "example": "Fully rounded (pills, circles)"
  },
  {
    "name": "--lb-size-2xs",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-2xs",
    "example": ""
  },
  {
    "name": "--lb-size-xs",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-xs",
    "example": ""
  },
  {
    "name": "--lb-size-sm",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-sm",
    "example": ""
  },
  {
    "name": "--lb-size-md",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-md",
    "example": ""
  },
  {
    "name": "--lb-size-lg",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-lg",
    "example": ""
  },
  {
    "name": "--lb-size-xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-xl",
    "example": ""
  },
  {
    "name": "--lb-size-2xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-2xl",
    "example": ""
  },
  {
    "name": "--lb-size-3xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-3xl",
    "example": ""
  },
  {
    "name": "--lb-size-4xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-4xl",
    "example": ""
  },
  {
    "name": "--lb-size-5xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-5xl",
    "example": ""
  },
  {
    "name": "--lb-size-6xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-6xl",
    "example": ""
  },
  {
    "name": "--lb-size-7xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-7xl",
    "example": ""
  },
  {
    "name": "--lb-size-8xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-8xl",
    "example": ""
  },
  {
    "name": "--lb-size-9xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-9xl",
    "example": ""
  },
  {
    "name": "--lb-size-10xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-10xl",
    "example": ""
  },
  {
    "name": "--lb-size-11xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-11xl",
    "example": ""
  },
  {
    "name": "--lb-size-12xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-size-12xl",
    "example": ""
  },
  {
    "name": "--lb-chip-height",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-chip-height",
    "example": ""
  },
  {
    "name": "--lb-chip-padding-x",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-chip-padding-x",
    "example": ""
  },
  {
    "name": "--lb-chip-font-size",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-chip-font-size",
    "example": ""
  },
  {
    "name": "--lb-chip-icon-size",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-chip-icon-size",
    "example": ""
  },
  {
    "name": "--lb-chip-avatar-size",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-chip-avatar-size",
    "example": ""
  },
  {
    "name": "--lb-chip-border-radius",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-chip-border-radius",
    "example": ""
  },
  {
    "name": "--lb-opacity-0",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-0",
    "example": ""
  },
  {
    "name": "--lb-opacity-10",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-10",
    "example": ""
  },
  {
    "name": "--lb-opacity-20",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-20",
    "example": ""
  },
  {
    "name": "--lb-opacity-30",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-30",
    "example": ""
  },
  {
    "name": "--lb-opacity-40",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-40",
    "example": ""
  },
  {
    "name": "--lb-opacity-50",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-50",
    "example": ""
  },
  {
    "name": "--lb-opacity-60",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-60",
    "example": ""
  },
  {
    "name": "--lb-opacity-70",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-70",
    "example": ""
  },
  {
    "name": "--lb-opacity-80",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-80",
    "example": ""
  },
  {
    "name": "--lb-opacity-90",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-90",
    "example": ""
  },
  {
    "name": "--lb-opacity-100",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-opacity-100",
    "example": ""
  },
  {
    "name": "--lb-shadow-sm",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-shadow-sm",
    "example": ""
  },
  {
    "name": "--lb-shadow-md",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-shadow-md",
    "example": ""
  },
  {
    "name": "--lb-shadow-lg",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-shadow-lg",
    "example": ""
  },
  {
    "name": "--lb-transition-fast",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-transition-fast",
    "example": ""
  },
  {
    "name": "--lb-transition-normal",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-transition-normal",
    "example": ""
  },
  {
    "name": "--lb-transition-slow",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-transition-slow",
    "example": ""
  },
  {
    "name": "--lb-input-height-md",
    "category": "Input",
    "subcategory": "",
    "description": "Input height",
    "usage": "height: var(--lb-input-height-md);",
    "example": ""
  },
  {
    "name": "--lb-input-height-lg",
    "category": "Input",
    "subcategory": "",
    "description": "Input height",
    "usage": "height: var(--lb-input-height-lg);",
    "example": ""
  },
  {
    "name": "--lb-font-heading",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-heading",
    "example": ""
  },
  {
    "name": "--lb-font-body",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-body",
    "example": ""
  },
  {
    "name": "--lb-font-label",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-label",
    "example": ""
  },
  {
    "name": "--lb-font-mono",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-mono",
    "example": ""
  },
  {
    "name": "--lb-font-weight-thin",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-thin",
    "example": ""
  },
  {
    "name": "--lb-font-weight-extralight",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-extralight",
    "example": ""
  },
  {
    "name": "--lb-font-weight-light",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-light",
    "example": ""
  },
  {
    "name": "--lb-font-weight-regular",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-regular",
    "example": ""
  },
  {
    "name": "--lb-font-weight-medium",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-medium",
    "example": ""
  },
  {
    "name": "--lb-font-weight-semibold",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-semibold",
    "example": ""
  },
  {
    "name": "--lb-font-weight-bold",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-bold",
    "example": ""
  },
  {
    "name": "--lb-font-weight-extrabold",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-extrabold",
    "example": ""
  },
  {
    "name": "--lb-font-weight-black",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-black",
    "example": ""
  },
  {
    "name": "--lb-font-weight-heading",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-heading",
    "example": ""
  },
  {
    "name": "--lb-font-weight-body",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-body",
    "example": ""
  },
  {
    "name": "--lb-font-weight-label",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-weight-label",
    "example": ""
  },
  {
    "name": "--lb-line-height-tight",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-line-height-tight",
    "example": ""
  },
  {
    "name": "--lb-line-height-compact",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-line-height-compact",
    "example": ""
  },
  {
    "name": "--lb-line-height-normal",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-line-height-normal",
    "example": ""
  },
  {
    "name": "--lb-line-height-relaxed",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-line-height-relaxed",
    "example": ""
  },
  {
    "name": "--lb-font-size-body-sm",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-body-sm",
    "example": ""
  },
  {
    "name": "--lb-font-size-body-base",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-body-base",
    "example": ""
  },
  {
    "name": "--lb-font-size-body-lg",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-body-lg",
    "example": ""
  },
  {
    "name": "--lb-font-size-body-xl",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-body-xl",
    "example": ""
  },
  {
    "name": "--lb-font-size-label-xs",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-label-xs",
    "example": ""
  },
  {
    "name": "--lb-font-size-label-sm",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-label-sm",
    "example": ""
  },
  {
    "name": "--lb-font-size-label-base",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-label-base",
    "example": ""
  },
  {
    "name": "--lb-font-size-label-lg",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-font-size-label-lg",
    "example": ""
  },
  {
    "name": "--lb-letter-spacing-tighter",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-letter-spacing-tighter",
    "example": ""
  },
  {
    "name": "--lb-letter-spacing-tight",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-letter-spacing-tight",
    "example": ""
  },
  {
    "name": "--lb-letter-spacing-normal",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-letter-spacing-normal",
    "example": ""
  },
  {
    "name": "--lb-letter-spacing-wide",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-letter-spacing-wide",
    "example": ""
  },
  {
    "name": "--lb-display-1",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-display-1",
    "example": ""
  },
  {
    "name": "--lb-display-2",
    "category": "Other",
    "subcategory": "",
    "description": "",
    "usage": "Use in CSS: --lb-display-2",
    "example": ""
  },
  {
    "name": "--lb-text-light-normal",
    "category": "Text",
    "subcategory": "light",
    "description": "Light text color (normal contrast)",
    "usage": "color: var(--lb-text-light-normal);",
    "example": "Text color for light content"
  },
  {
    "name": "--lb-text-light-contrast-low",
    "category": "Text",
    "subcategory": "light",
    "description": "Light text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-light-contrast-low);",
    "example": "Text color for light content"
  },
  {
    "name": "--lb-text-dark-normal",
    "category": "Text",
    "subcategory": "dark",
    "description": "Dark text color (normal contrast)",
    "usage": "color: var(--lb-text-dark-normal);",
    "example": "Text color for dark content"
  },
  {
    "name": "--lb-text-dark-contrast-low",
    "category": "Text",
    "subcategory": "dark",
    "description": "Dark text color (contrast-low contrast)",
    "usage": "color: var(--lb-text-dark-contrast-low);",
    "example": "Text color for dark content"
  }
];

// Helper functions
export const getTokensByCategory = (category: string): DesignToken[] => {
  return tokens.filter(t => t.category === category);
};

export const getTokensBySubcategory = (category: string, subcategory: string): DesignToken[] => {
  return tokens.filter(t => t.category === category && t.subcategory === subcategory);
};

export const searchTokens = (query: string): DesignToken[] => {
  const lowerQuery = query.toLowerCase();
  return tokens.filter(t =>
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery) ||
    t.category.toLowerCase().includes(lowerQuery) ||
    t.subcategory?.toLowerCase().includes(lowerQuery)
  );
};

export const getTokenByName = (name: string): DesignToken | undefined => {
  // Allow with or without -- prefix
  const normalized = name.startsWith('--') ? name : `--${name}`;
  return tokens.find(t => t.name === normalized);
};
